version: '2'
services:
  db:
    container_name: TeamRewardsApp-10010-db
    build: db
    image: teamrewardsapp-10010/db
    ports:
      - "32657:3306"
  node:
    depends_on:
      - db

    container_name: TeamRewardsApp-10010-web
    build: desktop
    image: teamrewardsapp-10010/web
    links:
      - db:mydb

    ports:
      - "9090:8080"
