/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC </br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/


USE teamrewardsapp;

CREATE TABLE Nomination(
id bigint(19) NOT NULL auto_increment,
created_date datetime NOT NULL DEFAULT NOW(),
created_by bigint(19) NOT NULL DEFAULT 0,
updated_date datetime NOT NULL DEFAULT NOW(),
updated_by bigint(19) NOT NULL DEFAULT 0,
nominator varchar(255),
nominator_los varchar(255),
team_name varchar(255),
project_name varchar(255),
is_team char(1),
is_individual varchar(255),
team_desc varchar(255),
team_notes varchar(255),
prime_adjst varchar(255),
sec_adjst varchar(255),
award_total varchar(255),
award_category varchar(255),
behaviors varchar(255),
is_current_audit_client varchar(255),
one_firm_metric varchar(255),
status varchar(255),
list_leader_reviewer varchar(255),
nominees varchar(255),
leader_reviewers varchar(255),
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Nominee(
id bigint(19) NOT NULL auto_increment,
created_date datetime NOT NULL DEFAULT NOW(),
created_by bigint(19) NOT NULL DEFAULT 0,
updated_date datetime NOT NULL DEFAULT NOW(),
updated_by bigint(19) NOT NULL DEFAULT 0,
name varchar(255),
person_no varchar(255),
manager varchar(255),
email varchar(255),
line varchar(255),
award_type varchar(255),
award_amount varchar(255),
notes varchar(255),
status varchar(255),
dept_id varchar(255),
region varchar(255),
market varchar(255),
initial_contribution_level varchar(255),
final_contribution_level varchar(255),
Nomination_id bigint(19) NOT NULL,
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Leader_reviewer(
id bigint(19) NOT NULL auto_increment,
created_date datetime NOT NULL DEFAULT NOW(),
created_by bigint(19) NOT NULL DEFAULT 0,
updated_date datetime NOT NULL DEFAULT NOW(),
updated_by bigint(19) NOT NULL DEFAULT 0,
leader_name varchar(255),
guid varchar(255),
status varchar(255),
is_edit_request varchar(255),
is_wording_accurate varchar(255),
suggest_rank varchar(255),
comments varchar(255),
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

